# S03 T04: Pràctica amb programació numèrica (*NumPy*)

---------------------------------------------------------------------------------------

### Nivell 1- Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [1]:
#imports
import numpy as np
from numpy import random

# creating int random values array from user inputs
try:
    max_val = int(input("Escriu el valor màxim que tindrà l'array:"))
    q = int(input("Escriu la quantitat de valors que tindrà l'array:"))

    np_llista = random.randint(max_val, size=(q))
    print(np_llista)
except ValueError as ve:
    print("Has d'introduir valors de tipus 'integer': ", ve)

Escriu el valor màxim que tindrà l'array:6
Escriu la quantitat de valors que tindrà l'array:6
[5 5 5 1 4 0]


In [4]:
# function definition
def estadistiques(arr):
    if arr.ndim > 1:
        raise ValueError("La matriu té més d'una dimensió.")
    else:
        print("--- estadistiques bàsiques ---")
        print("------------------------------")
        print("Shape:", arr.shape)
        print("Dimensions:", arr.ndim)
        print("Mitjana:", np.mean(arr))
        print("Mediana:", np.median(arr))
        print("Average:", np.average(arr))
        print("Suma dels elements:", np.sum(arr))
        print("Valor max:", np.max(arr))
        print("Valor min:", np.min(arr))
        print("Rang:", np.ptp(arr))
        print("Desviació estàndar:", np.std(arr))
        print("Coeficient correlació Pearson:", np.corrcoef(arr))
        print("Percentil 50:", np.percentile(arr, 50))
        print("Histograma:", np.histogram(arr))
        

In [5]:
# function call
estadistiques(np_llista)

--- estadistiques bàsiques ---
------------------------------
Shape: (6,)
Dimensions: 1
Mitjana: 3.3333333333333335
Mediana: 4.5
Average: 3.3333333333333335
Suma dels elements: 20
Valor max: 5
Valor min: 0
Rang: 5
Desviació estàndar: 2.0548046676563256
Coeficient correlació Pearson: 1.0
Percentil 50: 4.5
Histograma: (array([1, 0, 1, 0, 0, 0, 0, 0, 1, 3], dtype=int64), array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]))


----------------------------------------------------------------------------

### Nivell 1 - Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [6]:
# function v1
#the input parameter must be an int
def array_NxN(n):
    #creating a random array with NxN values
    arr = random.randint(101, size = (n,n))
    return arr

In [7]:
#value to pass as parameter to the function
num = 7

#invoking function v1
matriu = array_NxN(num)
print("m:",matriu)


m: [[43 23 78 15 48 30 49]
 [42 84 17 63 20 41 42]
 [ 3 83 51 65 35 95 50]
 [33 17 40 91 10 70 42]
 [59 75 74 87 12 36 68]
 [69 40 23 30 22 54 54]
 [70 85 92 46 33 96 55]]


________________________________________

### Nivell 1 - Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 


In [138]:
#function total axis
#the input parameter must be a 2D array and return 2 lists
#rows --> arr.shape[0]
#columns --> arr.shape[1]

def totals_axis(a):
    totals_rows = [] #empty list to save the totals for each row
    totals_cols = [] #empty list to save the totals for each column
    
    #testing if a it's a 2D array
    if a.ndim != 2:
        print("La matriu usada no té dues dimensions!")
    else:
        #rows totals
        for i in range(a.shape[0]):
            r = np.sum(a[i,:])
            totals_rows.append(r)

        #cols totals
        for i in range(a.shape[1]):
            c = np.sum(a[:,i])
            totals_cols.append(c)
            
        return totals_rows, totals_cols    
    

In [142]:
#calling the function
files, columnes = totals_axis(matriu)
print("Totals de cada fila: ", files)
print("Totals de cada columna: ", columnes)

Totals de cada fila:  [326, 406, 339, 368, 342, 300, 241]
Totals de cada columna:  [301, 378, 279, 364, 392, 311, 297]


______________________________________________________________________________________________

### Nivell 1 - Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

-- **COEFICIENT DE CORRELACIÓ de PEARSON** --

El coeficient de correlació de Pearson és un índex que mesura la relació lineal entre dues variables quantitatives.
Sempre fluctuarà entre –1 i +1, i indicarà relacions fortes a mida que el  valor  s’acosti  als  extrems.
> A  un  núvol  de  punts  aproximadament  lineal  amb  pendent descendent li correspondrà un valor pròxim a –1, i indicarà una relació inversa o negativa.

> A  un  núvol  de  punts  aproximadament  lineal  amb  pendent  ascendent  li  correspondrà  un  valor pròxim a +1, i indicarà una relació directa o positiva.

> Un valor zero indica absència de relació lineal entre les variables.

NO serveix per detectar valors atípics en les dades, i tampoc detecta correctament les relacions curvilínies.

In [68]:
#function definition
def coef_pearson(a1, a2):
    try: 
        #check if the dimension or the lenght ar ok
        if a1.ndim != 1 or a2.ndim != 1:
             print("The inputs must be 1D arrays.")
        elif len(a1) != len(a2):
            print("The arrays must have the same lenght.")
        else:
            num = np.sum((a1-np.mean(a1))*(a2-np.mean(a2)))
            denom = np.sqrt(np.sum((a1-np.mean(a1))**2))*np.sqrt(np.sum((a2-np.mean(a2))**2))
            resultat = num/denom
    
            return resultat
    except:
        print("Input error: The inputs must be 1D arrays.")

Porvem la funció fet una crida amb diferents valors:

In [70]:
#np_x = 3 
#np_y = 8 

#np_x = np.array([14,1,  146, 418, 220])
#np_y = np.array([33, 39, 45])

np_x = np.array([14,1,  146, 418, 220])
np_y = np.array([24, 30, 33, 39, 45])

r = coef_pearson(np_x, np_y)
print(r)

0.732355601740743


In [71]:
print("Coeficient correlació Pearson:", np.corrcoef(np_x, np_y))

Coeficient correlació Pearson: [[1.        0.7323556]
 [0.7323556 1.       ]]
